### ISSUE TITLE
Implement GitHub Actions for automated issue lifecycle management

### ISSUE THREAD

**Issue by timmybird** [PitchConnect/strategic-planning#18]
# Implement GitHub Actions for automated issue lifecycle management

## Description
We need to implement GitHub Actions that automate the issue lifecycle management across our repositories. This will standardize how we track issues through the development process and ensure consistent practices.

## Background
Currently, issue status tracking is manual and inconsistent. We want to automate this process to:
1. Track issues referenced in PRs
2. Update issue labels based on PR status
3. Generate comprehensive release notes
4. Close issues at the appropriate time

## Tasks
- [ ] Create a GitHub Action for PR status tracking that:
  - [ ] Labels issues as `in-progress` when referenced in Draft PRs
  - [ ] Updates labels to `review-ready` when PRs are marked ready
  - [ ] Adds `merged-to-develop` label when PRs are merged to develop
  - [ ] Adds comments to issues at each stage

- [ ] Create a GitHub Action for release management that:
  - [ ] Collects all issues with `merged-to-develop` label
  - [ ] Automatically includes them in release PRs
  - [ ] Ensures issues are closed when merged to main
  - [ ] Adds `released` label to closed issues

- [ ] Test the actions in a development environment
- [ ] Document the actions in the contribution guidelines
- [ ] Deploy the actions to all repositories

### PR Status Tracking Action
```yaml
name: PR Status Tracking

on:
  pull_request:
    types: [opened, converted_to_draft, ready_for_review, closed]

jobs:
  track-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Track Issue Status
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const pr = context.payload.pull_request;
            
            // Extract issue numbers from PR body
            const issueRefs = pr.body.match(/(close[sd]?|fix(es|ed)?|resolve[sd]?)\s*:?\s*#(\d+)/gi) || [];
            const issueNumbers = issueRefs.map(ref => parseInt(ref.match(/#(\d+)/)[1]));
            
            if (issueNumbers.length === 0) {
              console.log('No issue references found in PR');
              return;
            }
            
            // Process each referenced issue
            for (const issueNumber of issueNumbers) {
              // Handle different PR states
              if (pr.draft) {
                // PR is a draft - add in-progress label
                await github.rest.issues.addLabels({
                  owner, repo, issue_number: issueNumber,
                  labels: ['in-progress']
                });
                
                await github.rest.issues.createComment({
                  owner, repo, issue_number: issueNumber,
                  body: `This issue is being worked on in draft PR #${pr.number}`
                });
              } 
              else if (pr.state === 'open' && !pr.draft) {
                // PR is ready for review
                try {
                  await github.rest.issues.removeLabel({
                    owner, repo, issue_number: issueNumber,
                    name: 'in-progress'
                  });
                } catch (e) {}
                
                await github.rest.issues.addLabels({
                  owner, repo, issue_number: issueNumber,
                  labels: ['review-ready']
                });
                
                await github.rest.issues.createComment({
                  owner, repo, issue_number: issueNumber,
                  body: `Work on this issue is ready for review in PR #${pr.number}`
                });
              } 
              else if (pr.state === 'closed' && pr.merged) {
                // PR was merged
                const targetBranch = pr.base.ref;
                
                if (targetBranch === 'develop') {
                  try {
                    await github.rest.issues.removeLabel({
                      owner, repo, issue_number: issueNumber,
                      name: 'review-ready'
                    });
                  } catch (e) {}
                  
                  await github.rest.issues.addLabels({
                    owner, repo, issue_number: issueNumber,
                    labels: ['merged-to-develop']
                  });
                  
                  await github.rest.issues.createComment({
                    owner, repo, issue_number: issueNumber,
                    body: `Implementation for this issue has been merged to the develop branch in PR #${pr.number}`
                  });
                }
              }
            }
```

### Release Management Action
```yaml
name: Generate Release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., 1.2.0)'
        required: true

jobs:
  create-release-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Create Release Branch
        run: |
          git checkout develop
          git pull
          git checkout -b release/v${{ github.event.inputs.version }}
          git push -u origin release/v${{ github.event.inputs.version }}
      
      - name: Collect Pending Issues
        id: collect-issues
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            
            // Get all issues with 'merged-to-develop' label
            const { data: issues } = await github.rest.issues.listForRepo({
              owner, repo, state: 'open', labels: 'merged-to-develop'
            });
            
            // Format issues for PR description
            let issueList = '';
            let issueRefs = '';
            
            issues.forEach(issue => {
              issueList += `- #${issue.number}: ${issue.title}\n`;
              issueRefs += `Fixes #${issue.number}\n`;
            });
            
            return { issueList, issueRefs };
      
      - name: Create Release PR
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const version = '${{ github.event.inputs.version }}';
            const { issueList, issueRefs } = ${{ steps.collect-issues.outputs.result }};
            
            const body = `# Release v${version}
            
            ## Issues included in this release:
            ${issueList}
            
            ## Changelog
            [Add release notes here]
            
            ${issueRefs}`;
            
            await github.rest.pulls.create({
              owner, repo, title: `Release v${version}`,
              head: `release/v${version}`, base: 'main', body: body
            });
```

## Benefits
- Standardized issue tracking across repositories
- Automated status updates reduce manual work
- Clear visibility into issue status
- Comprehensive release notes
- Ensures issues are closed at the right time
- Supports our GitFlow branching model

## Related to
This is related to issue #7 "Add Issue Lifecycle and Automation section to contribution guidelines" and our overall effort to improve contribution processes.

Please follow the guidelines in [CONTRIBUTING.md](https://github.com/PitchConnect/contribution-guidelines) when working on this issue.
